# 数据集参数
dataset_conf:
#  # 训练数据的数据列表路径
#  train_list: './dlkit/data_utils/konface_train_val_list_single.txt'
#  # 测试数据的数据列表路径
#  test_list: './dlkit/data_utils/konface_test_list_single.txt'
#  # 标签列表
#  label_list_path: './dlkit/data_utils/konface_label_list.txt'

  # 训练数据的数据列表路径
  train_list: './dlkit/data_utils/catdog_train_list.txt'
  # 测试数据的数据列表路径
  test_list: './dlkit/data_utils/catdog_valid_list.txt'
  # 标签列表
  label_list_path: './dlkit/data_utils/catdog_label_list.txt'
  # 评估的数据要特殊处理
  eval_conf:
    # 评估的批量大小
    batch_size: 64
  # 数据加载器参数
  dataLoader:
    # 训练的批量大小
    batch_size: 64
    # 读取数据的线程数量
    num_workers: 4

optimizer_conf:
  # 优化方法，支持Adam、AdamW、SGD
  optimizer: 'Adam'
  # 初始学习率的大小
  learning_rate: 0.001
  weight_decay: !!float 1e-6
  # 学习率衰减函数，支持WarmupCosineSchedulerLR、CosineAnnealingLR
  scheduler: 'WarmupCosineSchedulerLR'
  # 学习率衰减函数参数
  scheduler_args:
    min_lr: !!float 1e-5
    max_lr: 0.001
    warmup_epoch: 5

model_conf:
  # 分类大小，如果为null，自动通过标签列表获取
  num_class: null
  # 所使用的池化层，支持ASP、SAP、TSP、TAP
  pooling_type: 'ASP'

train_conf:
  # 是否开启自动混合精度
  enable_amp: False
  # 是否使用Pytorch2.0的编译器
  use_compile: False
  # CrossEntropyLoss类的weight参数
  loss_weight: null
  # 训练的轮数
  max_epoch: 60
  log_interval: 10

# 所使用的模型
use_model: 'AlexNet'